language: python
python:
  # Only 2.7 to prevent having to install NumPy and SciPy from source.
  - "2.7"

services:
  - elasticsearch
  - rabbitmq

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy
  - pip install .
  - pip install -r requirements.txt
  - wget http://nlp.stanford.edu/software/stanford-corenlp-full-2014-06-16.zip -O temp.zip
  - unzip temp.zip
  - export CORENLP_HOME=`pwd`/stanford-corenlp-full-2014-06-16

script:
  - python -m xtas.worker --loglevel=info --pidfile=worker.pid &
  - nosetests -s -v --exe xtas
  - testexit=$?
  - kill $(cat worker.pid)
  - (exit $testexit)
